### ISSUE TITLE
When cloning a repository, check if no plugins use the same id

### ISSUE THREAD

**Issue by Blatoy** [forwards-long-jump/discotron#25]
For exemple, adding
https://github.com/Blatoy/discotron-general-plugins.git
and 
https://github.com/Blatoy/discotron-general-plugins
will work, but it will break a lot of things internally

**Comment by RedMser** [comment]
...in specific, when deleting one of the two (in my case, tested with http and https as the two identical repos), the files still seem to be lying around, and deleting/adding that specific repo does not work until the files are manually removed.
