### ISSUE TITLE
Add a CSS and HTML linter

### ISSUE THREAD

**Issue by Blatoy** [forwards-long-jump/discotron#76]
We should really use a html and css linter as well

_Originally posted by @Blatoy in https://github.com/forwards-long-jump/discotron/pull/75/review_comment/create_

**Comment by s-arika** [comment]
Could I work on the css linter portion? Would you be open to using stylelint?

**Comment by Blatoy** [comment]
I've quickly checked stylelint and it looks good, feel free to work on that!
